package schema

var WorkItemOwnerDecisionsTableSQL = `CREATE TABLE IF NOT EXISTS work_item_owner_decisions (id TEXT PRIMARY KEY, work_item_id TEXT NOT NULL REFERENCES work_items(id) ON DELETE CASCADE, completion_report_id TEXT REFERENCES work_item_completion_reports(id), decision TEXT NOT NULL CHECK(decision IN ('accepted','rejected','deferred')), question_id TEXT NOT NULL DEFAULT '', rri_artifact_id TEXT NOT NULL DEFAULT '', notes TEXT DEFAULT '', decided_by_role TEXT NOT NULL DEFAULT '', created_at TEXT DEFAULT (datetime('now')))`

var CanonicalSchemaStatements = []string{
	WorkItemsTableSQL,
	`CREATE TABLE IF NOT EXISTS work_item_labels (work_item_id TEXT NOT NULL REFERENCES work_items(id) ON DELETE CASCADE, label TEXT NOT NULL, PRIMARY KEY(work_item_id,label))`,
	`CREATE TABLE IF NOT EXISTS work_item_dependencies (id TEXT PRIMARY KEY, work_item_id TEXT NOT NULL REFERENCES work_items(id) ON DELETE CASCADE, depends_on_work_item_id TEXT NOT NULL REFERENCES work_items(id) ON DELETE CASCADE, created_at TEXT DEFAULT (datetime('now')), UNIQUE(work_item_id,depends_on_work_item_id), CHECK(work_item_id!=depends_on_work_item_id))`,
	`CREATE TABLE IF NOT EXISTS work_item_gates (id TEXT PRIMARY KEY, work_item_id TEXT NOT NULL REFERENCES work_items(id) ON DELETE CASCADE, gate_work_item_id TEXT NOT NULL REFERENCES work_items(id) ON DELETE CASCADE, created_at TEXT DEFAULT (datetime('now')), UNIQUE(work_item_id,gate_work_item_id), CHECK(work_item_id!=gate_work_item_id))`,
	`CREATE TABLE IF NOT EXISTS work_item_relations (id TEXT PRIMARY KEY, work_item_id TEXT NOT NULL REFERENCES work_items(id) ON DELETE CASCADE, relation_type TEXT NOT NULL CHECK(relation_type IN ('blocks','gates','related')), related_work_item_id TEXT NOT NULL REFERENCES work_items(id) ON DELETE CASCADE, created_at TEXT DEFAULT (datetime('now')), UNIQUE(work_item_id,relation_type,related_work_item_id), CHECK(work_item_id!=related_work_item_id))`,
	WorkItemArtifactsTableSQL,
	WorkflowCheckpointsTableSQL,
	`CREATE TABLE IF NOT EXISTS implementation_authorizations (id TEXT PRIMARY KEY, work_item_id TEXT NOT NULL REFERENCES work_items(id) ON DELETE CASCADE, task_graph_checkpoint_id TEXT NOT NULL REFERENCES workflow_checkpoints(id), authorized_by TEXT NOT NULL, revoked_at TEXT DEFAULT '', created_at TEXT DEFAULT (datetime('now')))`,
	`CREATE TABLE IF NOT EXISTS work_item_materializations (root_work_item_id TEXT NOT NULL REFERENCES work_items(id) ON DELETE CASCADE, checkpoint_id TEXT NOT NULL REFERENCES workflow_checkpoints(id), node_key TEXT NOT NULL, work_item_id TEXT NOT NULL REFERENCES work_items(id) ON DELETE CASCADE, created_at TEXT DEFAULT (datetime('now')), PRIMARY KEY(root_work_item_id,checkpoint_id,node_key))`,
	`CREATE TABLE IF NOT EXISTS work_item_instruction_packs (id TEXT PRIMARY KEY, work_item_id TEXT NOT NULL REFERENCES work_items(id) ON DELETE CASCADE, checkpoint_id TEXT NOT NULL REFERENCES workflow_checkpoints(id), version INTEGER NOT NULL CHECK(version>0), status TEXT NOT NULL DEFAULT 'inactive' CHECK(status IN ('inactive','active','stale')), content_json TEXT NOT NULL, content_hash TEXT NOT NULL, activated_at TEXT DEFAULT '', stale_at TEXT DEFAULT '', created_at TEXT DEFAULT (datetime('now')), UNIQUE(work_item_id,version))`,
	`CREATE TABLE IF NOT EXISTS work_item_verification_reports (id TEXT PRIMARY KEY, work_item_id TEXT NOT NULL REFERENCES work_items(id) ON DELETE CASCADE, checkpoint_id TEXT DEFAULT '', completion_report_id TEXT REFERENCES work_item_completion_reports(id), status TEXT NOT NULL CHECK(status IN ('passed','failed','partial','blocked')), summary TEXT DEFAULT '', verified_by_role TEXT NOT NULL DEFAULT '', pipeline_high_water_rowid INTEGER NOT NULL DEFAULT 0, rri_t_json TEXT NOT NULL DEFAULT '', created_at TEXT DEFAULT (datetime('now')))`,
	`CREATE TABLE IF NOT EXISTS work_item_corrective_bugs (verification_report_id TEXT PRIMARY KEY REFERENCES work_item_verification_reports(id) ON DELETE CASCADE, bug_work_item_id TEXT NOT NULL UNIQUE REFERENCES work_items(id) ON DELETE CASCADE, owner_approval_required INTEGER NOT NULL DEFAULT 0, created_at TEXT DEFAULT (datetime('now')))`,
	WorkItemCompletionReportsTableSQL,
	WorkItemEscalationsTableSQL,
	WorkItemOwnerDecisionsTableSQL,
	`CREATE TABLE IF NOT EXISTS work_item_delivery_states (work_item_id TEXT PRIMARY KEY REFERENCES work_items(id) ON DELETE CASCADE, integration_mode TEXT NOT NULL CHECK(integration_mode IN ('branch','coordination')), branch_name TEXT DEFAULT '', base_branch TEXT DEFAULT 'develop', base_commit TEXT DEFAULT '', verified_head TEXT DEFAULT '', verification_report_id TEXT DEFAULT '', merge_status TEXT NOT NULL DEFAULT '' CHECK(merge_status IN ('','merge_pending','merged','blocked')), merged_commit TEXT DEFAULT '', merge_error TEXT DEFAULT '', updated_at TEXT DEFAULT (datetime('now')))`,
	`CREATE TABLE IF NOT EXISTS work_item_aggregate_owner_decisions (id TEXT PRIMARY KEY, work_item_id TEXT NOT NULL REFERENCES work_items(id) ON DELETE CASCADE, verification_report_id TEXT NOT NULL REFERENCES work_item_verification_reports(id), decision TEXT NOT NULL CHECK(decision IN ('accepted','rejected')), notes TEXT DEFAULT '', decided_by_role TEXT NOT NULL DEFAULT '', created_at TEXT DEFAULT (datetime('now')))`,
	`CREATE TABLE IF NOT EXISTS work_item_events (id TEXT PRIMARY KEY, work_item_id TEXT NOT NULL REFERENCES work_items(id) ON DELETE CASCADE, event_type TEXT NOT NULL, actor_role TEXT DEFAULT '', actor_model TEXT DEFAULT '', summary TEXT DEFAULT '', payload_json TEXT DEFAULT '', created_at TEXT DEFAULT (datetime('now')))`,
	OwnedWorkflowTableSQL["requirements"],
	OwnedWorkflowTableSQL["owner_decisions"],
	`CREATE TABLE IF NOT EXISTS session_activity (session_id TEXT PRIMARY KEY, task_id TEXT DEFAULT '', status TEXT DEFAULT 'idle' CHECK(status IN ('active','idle')), current_step_label TEXT DEFAULT '', last_skill TEXT DEFAULT '', updated_at TEXT DEFAULT (datetime('now')))`,
	PipelineRunsTableSQL,
	WorkItemProfilesTableSQL,
	`UPDATE work_items SET review_status='passed' WHERE status='done' AND type IN ('task','bug','chore') AND EXISTS (
			SELECT 1 FROM work_item_owner_decisions decision
			JOIN work_item_completion_reports completion ON completion.id=decision.completion_report_id AND completion.work_item_id=decision.work_item_id AND completion.status='done'
			JOIN work_item_instruction_packs pack ON pack.id=completion.instruction_pack_id AND pack.work_item_id=completion.work_item_id AND pack.version=completion.instruction_pack_version AND pack.content_hash=completion.instruction_pack_hash AND pack.status='active'
			JOIN work_item_verification_reports verification ON verification.work_item_id=completion.work_item_id AND verification.completion_report_id=completion.id AND verification.status='passed'
			WHERE decision.work_item_id=work_items.id AND decision.decision='accepted'
		)`,
	`CREATE INDEX IF NOT EXISTS idx_work_items_parent ON work_items(parent_id)`,
	`CREATE INDEX IF NOT EXISTS idx_work_items_status_claim ON work_items(type,status,deferred,claimed_at)`,
	`CREATE INDEX IF NOT EXISTS idx_work_item_labels_label ON work_item_labels(label)`,
	`CREATE INDEX IF NOT EXISTS idx_work_item_dependencies_item ON work_item_dependencies(work_item_id)`,
	`CREATE INDEX IF NOT EXISTS idx_work_item_dependencies_blocker ON work_item_dependencies(depends_on_work_item_id)`,
	`CREATE INDEX IF NOT EXISTS idx_work_item_gates_item ON work_item_gates(work_item_id)`,
	`CREATE INDEX IF NOT EXISTS idx_work_item_relations_item ON work_item_relations(work_item_id,relation_type)`,
	`CREATE INDEX IF NOT EXISTS idx_work_item_artifacts_item_stage ON work_item_artifacts(work_item_id,stage,revision DESC)`,
	`CREATE INDEX IF NOT EXISTS idx_workflow_checkpoints_item_stage ON workflow_checkpoints(work_item_id,stage,artifact_revision DESC)`,
	`CREATE INDEX IF NOT EXISTS idx_implementation_authorizations_item ON implementation_authorizations(work_item_id,created_at DESC)`,
	`CREATE INDEX IF NOT EXISTS idx_work_item_materializations_root ON work_item_materializations(root_work_item_id,checkpoint_id)`,
	`CREATE UNIQUE INDEX IF NOT EXISTS idx_work_item_instruction_packs_active ON work_item_instruction_packs(work_item_id) WHERE status='active'`,
	`CREATE INDEX IF NOT EXISTS idx_work_item_instruction_packs_checkpoint ON work_item_instruction_packs(checkpoint_id,status)`,
	`CREATE INDEX IF NOT EXISTS idx_work_item_verification_reports_item ON work_item_verification_reports(work_item_id,created_at DESC)`,
	`CREATE INDEX IF NOT EXISTS idx_work_item_completion_reports_item ON work_item_completion_reports(work_item_id,created_at DESC)`,
	`CREATE INDEX IF NOT EXISTS idx_work_item_owner_decisions_item ON work_item_owner_decisions(work_item_id,created_at DESC)`,
	`CREATE INDEX IF NOT EXISTS idx_work_item_delivery_states_status ON work_item_delivery_states(merge_status,integration_mode)`,
	`CREATE INDEX IF NOT EXISTS idx_work_item_aggregate_owner_decisions_item ON work_item_aggregate_owner_decisions(work_item_id,created_at DESC)`,
	`CREATE INDEX IF NOT EXISTS idx_work_item_events_item ON work_item_events(work_item_id,created_at DESC)`,
	`CREATE UNIQUE INDEX IF NOT EXISTS idx_requirements_task_key ON requirements(task_id,requirement_key) WHERE task_id IS NOT NULL`,
	`CREATE UNIQUE INDEX IF NOT EXISTS idx_requirements_epic_key ON requirements(epic_id,requirement_key) WHERE epic_id IS NOT NULL`,
	`CREATE INDEX IF NOT EXISTS idx_requirements_task ON requirements(task_id)`,
	`CREATE INDEX IF NOT EXISTS idx_requirements_contract_key ON requirements(contract_key) WHERE contract_key!=''`,
	`CREATE INDEX IF NOT EXISTS idx_pipeline_runs_task ON pipeline_runs(task_id, created_at DESC)`,
	`CREATE INDEX IF NOT EXISTS idx_work_item_profiles_item ON work_item_profiles(work_item_id,profile_name)`,
	`CREATE INDEX IF NOT EXISTS idx_pipeline_runs_pending ON pipeline_runs(advanced_at,status,task_id)`,
	`CREATE UNIQUE INDEX IF NOT EXISTS idx_pipeline_runs_active_stage ON pipeline_runs(task_id, stage) WHERE status IN ('claimed','running')`,
	`CREATE TRIGGER IF NOT EXISTS trg_work_item_artifact_immutable BEFORE UPDATE ON work_item_artifacts BEGIN SELECT RAISE(ABORT,'work item artifacts are immutable'); END`,
	`DROP TRIGGER IF EXISTS trg_work_item_artifact_delete_immutable`,
	`CREATE TRIGGER trg_work_item_artifact_delete_immutable BEFORE DELETE ON work_item_artifacts WHEN EXISTS(SELECT 1 FROM workflow_checkpoints WHERE artifact_id=OLD.id) BEGIN SELECT RAISE(ABORT,'approved work item artifacts are immutable'); END`,
	`CREATE TRIGGER IF NOT EXISTS trg_work_item_pack_immutable BEFORE UPDATE OF work_item_id,checkpoint_id,version,content_json,content_hash ON work_item_instruction_packs BEGIN SELECT RAISE(ABORT,'work item instruction packs are immutable'); END`,
	`CREATE TRIGGER IF NOT EXISTS trg_keyed_requirement_content_immutable BEFORE UPDATE OF requirement_key,contract_key,inherit_to_descendants,title,description,acceptance_criteria ON requirements WHEN OLD.contract_key!='' BEGIN SELECT RAISE(ABORT,'keyed requirement content is immutable; create a replacement requirement'); END`,
}

var LegacySchemaStatements = []string{
	`CREATE TABLE IF NOT EXISTS epics (
			id TEXT PRIMARY KEY,
			title TEXT NOT NULL,
			description TEXT DEFAULT '',
			workflow_mode TEXT DEFAULT 'full' CHECK(workflow_mode IN ('quick','standard','designed','full')),
			design_status TEXT DEFAULT '' CHECK(design_status IN ('','pending','approved','rejected')),
			owner_status TEXT DEFAULT '' CHECK(owner_status IN ('','pending','accepted','rejected')),
			status TEXT DEFAULT 'open' CHECK(status IN ('open','in_progress','done','cancelled')),
			created_at TEXT DEFAULT (datetime('now'))
		)`,
	`CREATE TABLE IF NOT EXISTS epic_events (id TEXT PRIMARY KEY, epic_id TEXT NOT NULL REFERENCES epics(id) ON DELETE CASCADE, event_type TEXT NOT NULL, actor_role TEXT DEFAULT '', actor_model TEXT DEFAULT '', summary TEXT DEFAULT '', payload_json TEXT DEFAULT '', created_at TEXT DEFAULT (datetime('now')))`,
	TasksTableSQL,
	`CREATE TABLE IF NOT EXISTS task_events (id TEXT PRIMARY KEY, task_id TEXT NOT NULL REFERENCES tasks(id) ON DELETE CASCADE, event_type TEXT NOT NULL, actor_role TEXT DEFAULT '', actor_model TEXT DEFAULT '', summary TEXT DEFAULT '', payload_json TEXT DEFAULT '', created_at TEXT DEFAULT (datetime('now')))`,
	OwnedWorkflowTableSQL["scan_reports"],
	OwnedWorkflowTableSQL["rri_sessions"],
	OwnedWorkflowTableSQL["designs"],
	`CREATE TABLE IF NOT EXISTS completion_reports (id TEXT PRIMARY KEY, task_id TEXT NOT NULL REFERENCES tasks(id) ON DELETE CASCADE, instruction_pack_id TEXT DEFAULT '', instruction_pack_version INTEGER DEFAULT 0, instruction_pack_hash TEXT DEFAULT '', effective_contract_snapshot_id TEXT DEFAULT '', effective_contract_snapshot_hash TEXT DEFAULT '', pipeline_run_id TEXT DEFAULT '', status TEXT NOT NULL CHECK(status IN ('done','partial','blocked','failed')), summary TEXT DEFAULT '', report_markdown TEXT DEFAULT '', files_changed_json TEXT DEFAULT '', tests_run_json TEXT DEFAULT '', acceptance_results_json TEXT DEFAULT '', issues_json TEXT DEFAULT '', deviations_json TEXT DEFAULT '', suggestions_json TEXT DEFAULT '', created_by_model TEXT DEFAULT '', created_at TEXT DEFAULT (datetime('now')))`,
	`CREATE TABLE IF NOT EXISTS task_materializations (task_id TEXT PRIMARY KEY REFERENCES tasks(id) ON DELETE CASCADE, epic_id TEXT NOT NULL REFERENCES epics(id) ON DELETE CASCADE, plan_node_key TEXT NOT NULL, design_id TEXT NOT NULL REFERENCES designs(id), design_version INTEGER NOT NULL, execution_policy TEXT DEFAULT 'strict_sequential' CHECK(execution_policy IN ('strict_sequential','partially_parallel','parallel_allowed','deferred_optional')), ordinal INTEGER NOT NULL, created_at TEXT DEFAULT (datetime('now')), UNIQUE(epic_id,plan_node_key,design_id))`,
	`CREATE TABLE IF NOT EXISTS task_instruction_packs (id TEXT PRIMARY KEY, display_key TEXT NOT NULL UNIQUE, task_id TEXT NOT NULL REFERENCES tasks(id) ON DELETE CASCADE, version INTEGER NOT NULL, status TEXT NOT NULL DEFAULT 'draft' CHECK(status IN ('draft','active','stale','superseded')), source_type TEXT NOT NULL CHECK(source_type IN ('epic_task_plan','standalone_task','standalone_design')), source_task_revision INTEGER NOT NULL, source_design_id TEXT DEFAULT '', source_design_version INTEGER DEFAULT 0, revision_kind TEXT NOT NULL DEFAULT 'initial' CHECK(revision_kind IN ('initial','scope','verification','contract','execution')), goal TEXT NOT NULL, module TEXT DEFAULT '', estimated_effort_minutes INTEGER DEFAULT 0, files_json TEXT NOT NULL, patterns_json TEXT NOT NULL, business_rules_json TEXT NOT NULL, validation_rules_json TEXT NOT NULL, error_handling_json TEXT NOT NULL, state_transitions_json TEXT NOT NULL, contract_obligations_json TEXT NOT NULL, constraints_json TEXT NOT NULL, verification_json TEXT NOT NULL, requirement_snapshots_json TEXT NOT NULL, content_schema_version INTEGER NOT NULL DEFAULT 1, skill_families_json TEXT NOT NULL DEFAULT '[]', effective_contract_snapshot_id TEXT DEFAULT '', effective_contract_snapshot_hash TEXT DEFAULT '', content_hash TEXT NOT NULL, activated_at TEXT DEFAULT '', stale_at TEXT DEFAULT '', superseded_at TEXT DEFAULT '', created_at TEXT DEFAULT (datetime('now')), UNIQUE(task_id,version))`,
	`CREATE TABLE IF NOT EXISTS instruction_pack_requirement_links (instruction_pack_id TEXT NOT NULL REFERENCES task_instruction_packs(id) ON DELETE CASCADE, requirement_id TEXT NOT NULL REFERENCES requirements(id), created_at TEXT DEFAULT (datetime('now')), PRIMARY KEY(instruction_pack_id,requirement_id))`,
	OwnedWorkflowTableSQL["verification_reports"],
	`CREATE TABLE IF NOT EXISTS verification_items (id TEXT PRIMARY KEY, verification_report_id TEXT NOT NULL REFERENCES verification_reports(id) ON DELETE CASCADE, requirement_id TEXT REFERENCES requirements(id) ON DELETE SET NULL, status TEXT NOT NULL CHECK(status IN ('pass','fail','partial','deferred','not_applicable')), evidence TEXT DEFAULT '', notes TEXT DEFAULT '', "commit" TEXT DEFAULT '')`,
	OwnedWorkflowTableSQL["escalations"],
	`CREATE TABLE IF NOT EXISTS contract_operations (id TEXT PRIMARY KEY, task_id TEXT REFERENCES tasks(id) ON DELETE CASCADE, epic_id TEXT REFERENCES epics(id) ON DELETE CASCADE, operation_type TEXT NOT NULL CHECK(operation_type IN ('replace','withdraw','defer')), status TEXT NOT NULL DEFAULT 'draft' CHECK(status IN ('draft','approved','rejected')), inherit_to_descendants INTEGER NOT NULL DEFAULT 0 CHECK(inherit_to_descendants IN (0,1)), replacement_requirement_id TEXT REFERENCES requirements(id), resume_condition TEXT DEFAULT '' CHECK(resume_condition IN ('','subject_completed','owner_reactivation')), completed_task_impact TEXT NOT NULL DEFAULT 'none' CHECK(completed_task_impact IN ('none','review')), owner_decision_id TEXT REFERENCES owner_decisions(id), created_at TEXT DEFAULT (datetime('now')), approved_at TEXT DEFAULT '', reactivated_at TEXT DEFAULT '', CHECK((task_id IS NOT NULL) != (epic_id IS NOT NULL)), CHECK((operation_type='replace')=(replacement_requirement_id IS NOT NULL)))`,
	`CREATE TABLE IF NOT EXISTS contract_operation_targets (operation_id TEXT NOT NULL REFERENCES contract_operations(id) ON DELETE CASCADE, requirement_id TEXT NOT NULL REFERENCES requirements(id), PRIMARY KEY(operation_id,requirement_id))`,
	`CREATE TABLE IF NOT EXISTS effective_contract_snapshots (id TEXT PRIMARY KEY, task_id TEXT NOT NULL REFERENCES tasks(id) ON DELETE CASCADE, content_hash TEXT NOT NULL, created_at TEXT DEFAULT (datetime('now')))`,
	`CREATE TABLE IF NOT EXISTS effective_contract_entries (snapshot_id TEXT NOT NULL REFERENCES effective_contract_snapshots(id) ON DELETE CASCADE, requirement_id TEXT NOT NULL REFERENCES requirements(id), contract_key TEXT DEFAULT '', requirement_hash TEXT NOT NULL, status TEXT NOT NULL CHECK(status IN ('effective','excluded')), operation_id TEXT REFERENCES contract_operations(id), provenance TEXT NOT NULL, PRIMARY KEY(snapshot_id,requirement_id))`,
	`CREATE TABLE IF NOT EXISTS contract_task_impacts (operation_id TEXT NOT NULL REFERENCES contract_operations(id), task_id TEXT NOT NULL REFERENCES tasks(id), status TEXT NOT NULL DEFAULT 'contract_outdated' CHECK(status='contract_outdated'), created_at TEXT DEFAULT (datetime('now')), PRIMARY KEY(operation_id,task_id))`,
	`CREATE TABLE IF NOT EXISTS task_dependencies (id TEXT PRIMARY KEY, task_id TEXT NOT NULL REFERENCES tasks(id) ON DELETE CASCADE, depends_on_task_id TEXT NOT NULL REFERENCES tasks(id) ON DELETE CASCADE, dependency_type TEXT DEFAULT 'blocks' CHECK(dependency_type IN ('blocks','phase','related')), notes TEXT DEFAULT '', created_at TEXT DEFAULT (datetime('now')), UNIQUE(task_id, depends_on_task_id))`,
	`CREATE TABLE IF NOT EXISTS task_phase_metadata (task_id TEXT PRIMARY KEY REFERENCES tasks(id) ON DELETE CASCADE, parent_task_id TEXT REFERENCES tasks(id) ON DELETE SET NULL, phase_number INTEGER NOT NULL, phase_title TEXT DEFAULT '', execution_policy TEXT DEFAULT 'strict_sequential' CHECK(execution_policy IN ('strict_sequential','partially_parallel','parallel_allowed','deferred_optional')), is_deferrable INTEGER DEFAULT 0, can_start_before_previous INTEGER DEFAULT 0, created_at TEXT DEFAULT (datetime('now')))`,
	`CREATE INDEX IF NOT EXISTS idx_tasks_epic ON tasks(epic_id)`,
	`CREATE INDEX IF NOT EXISTS idx_epic_events_epic ON epic_events(epic_id)`,
	`CREATE UNIQUE INDEX IF NOT EXISTS idx_designs_task_version ON designs(task_id,version) WHERE task_id IS NOT NULL`,
	`CREATE UNIQUE INDEX IF NOT EXISTS idx_designs_epic_version ON designs(epic_id,version) WHERE epic_id IS NOT NULL`,
	`CREATE UNIQUE INDEX IF NOT EXISTS idx_instruction_packs_active_task ON task_instruction_packs(task_id) WHERE status='active'`,
	`CREATE INDEX IF NOT EXISTS idx_instruction_packs_task ON task_instruction_packs(task_id,version DESC)`,
	`CREATE INDEX IF NOT EXISTS idx_instruction_pack_requirements ON instruction_pack_requirement_links(requirement_id)`,
	`CREATE INDEX IF NOT EXISTS idx_task_events_task ON task_events(task_id)`,
	`CREATE INDEX IF NOT EXISTS idx_scan_reports_task ON scan_reports(task_id)`,
	`CREATE INDEX IF NOT EXISTS idx_rri_sessions_task ON rri_sessions(task_id)`,
	`CREATE INDEX IF NOT EXISTS idx_designs_task ON designs(task_id)`,
	`CREATE INDEX IF NOT EXISTS idx_completion_reports_task ON completion_reports(task_id)`,
	`CREATE UNIQUE INDEX IF NOT EXISTS idx_completion_reports_pipeline_run ON completion_reports(pipeline_run_id) WHERE pipeline_run_id!=''`,
	`CREATE INDEX IF NOT EXISTS idx_verification_reports_task ON verification_reports(task_id)`,
	`CREATE UNIQUE INDEX IF NOT EXISTS idx_verification_reports_pipeline_run ON verification_reports(pipeline_run_id) WHERE pipeline_run_id!=''`,
	`CREATE INDEX IF NOT EXISTS idx_verification_items_report ON verification_items(verification_report_id)`,
	`CREATE INDEX IF NOT EXISTS idx_escalations_task ON escalations(task_id)`,
	`CREATE INDEX IF NOT EXISTS idx_owner_decisions_task ON owner_decisions(task_id)`,
	`CREATE INDEX IF NOT EXISTS idx_contract_operations_task ON contract_operations(task_id,status)`,
	`CREATE INDEX IF NOT EXISTS idx_contract_operations_epic ON contract_operations(epic_id,status)`,
	`CREATE INDEX IF NOT EXISTS idx_contract_targets_requirement ON contract_operation_targets(requirement_id)`,
	`CREATE INDEX IF NOT EXISTS idx_contract_snapshots_task ON effective_contract_snapshots(task_id,created_at DESC)`,
	`CREATE INDEX IF NOT EXISTS idx_task_dependencies_task ON task_dependencies(task_id)`,
	`CREATE INDEX IF NOT EXISTS idx_task_dependencies_depends_on ON task_dependencies(depends_on_task_id)`,
	`CREATE INDEX IF NOT EXISTS idx_task_phase_metadata_parent ON task_phase_metadata(parent_task_id)`,
	`DROP TRIGGER IF EXISTS trg_instruction_pack_content_immutable`,
	`CREATE TRIGGER IF NOT EXISTS trg_instruction_pack_content_immutable BEFORE UPDATE OF task_id,version,source_type,source_task_revision,source_design_id,source_design_version,goal,module,estimated_effort_minutes,files_json,patterns_json,business_rules_json,validation_rules_json,error_handling_json,state_transitions_json,contract_obligations_json,constraints_json,verification_json,requirement_snapshots_json,content_schema_version,skill_families_json,effective_contract_snapshot_id,effective_contract_snapshot_hash,content_hash ON task_instruction_packs WHEN OLD.status!='draft' BEGIN SELECT RAISE(ABORT,'activated instruction pack content is immutable'); END`,
	`CREATE TRIGGER IF NOT EXISTS trg_instruction_pack_delete_immutable BEFORE DELETE ON task_instruction_packs WHEN OLD.status!='draft' BEGIN SELECT RAISE(ABORT,'activated instruction pack cannot be deleted'); END`,
	`CREATE TRIGGER IF NOT EXISTS trg_instruction_pack_links_insert_immutable BEFORE INSERT ON instruction_pack_requirement_links WHEN (SELECT status FROM task_instruction_packs WHERE id=NEW.instruction_pack_id)!='draft' BEGIN SELECT RAISE(ABORT,'activated instruction pack links are immutable'); END`,
	`CREATE TRIGGER IF NOT EXISTS trg_instruction_pack_links_update_immutable BEFORE UPDATE ON instruction_pack_requirement_links WHEN (SELECT status FROM task_instruction_packs WHERE id=OLD.instruction_pack_id)!='draft' BEGIN SELECT RAISE(ABORT,'activated instruction pack links are immutable'); END`,
	`CREATE TRIGGER IF NOT EXISTS trg_instruction_pack_links_delete_immutable BEFORE DELETE ON instruction_pack_requirement_links WHEN (SELECT status FROM task_instruction_packs WHERE id=OLD.instruction_pack_id)!='draft' BEGIN SELECT RAISE(ABORT,'activated instruction pack links are immutable'); END`,
	`DROP TRIGGER IF EXISTS trg_requirement_content_stales_packs`,
	`CREATE TRIGGER trg_requirement_content_stales_packs AFTER UPDATE OF requirement_key,title,description,acceptance_criteria ON requirements BEGIN UPDATE task_instruction_packs SET status='stale',stale_at=datetime('now') WHERE status='active' AND id IN (SELECT instruction_pack_id FROM instruction_pack_requirement_links WHERE requirement_id=NEW.id); UPDATE tasks SET review_status='pending',reviewed_instruction_pack_id='',owner_status='pending' WHERE id IN (SELECT task_id FROM task_instruction_packs WHERE status='stale' AND id IN (SELECT instruction_pack_id FROM instruction_pack_requirement_links WHERE requirement_id=NEW.id)); UPDATE verification_reports SET superseded_at=datetime('now') WHERE task_id IN (SELECT task_id FROM task_instruction_packs WHERE status='stale' AND id IN (SELECT instruction_pack_id FROM instruction_pack_requirement_links WHERE requirement_id=NEW.id)) AND superseded_at=''; UPDATE epics SET owner_status='pending' WHERE id IN (SELECT epic_id FROM tasks WHERE id IN (SELECT task_id FROM task_instruction_packs WHERE status='stale' AND id IN (SELECT instruction_pack_id FROM instruction_pack_requirement_links WHERE requirement_id=NEW.id))); END`,
}
