package schema

const PipelineRunsTableSQL = `CREATE TABLE IF NOT EXISTS pipeline_runs (id TEXT PRIMARY KEY, task_id TEXT NOT NULL REFERENCES work_items(id) ON DELETE CASCADE, stage TEXT NOT NULL CHECK(stage IN ('scan','rri','vision','blueprint','contracts','task_graph','worker','review','autofix')), attempt INTEGER NOT NULL, status TEXT NOT NULL DEFAULT 'claimed' CHECK(status IN ('claimed','running','completed','failed','blocked','cancelled','expired')), lease_token TEXT NOT NULL, lease_expires_at TEXT NOT NULL, instruction_pack_id TEXT DEFAULT '', instruction_pack_version INTEGER DEFAULT 0, instruction_pack_hash TEXT DEFAULT '', effective_contract_snapshot_id TEXT DEFAULT '', effective_contract_snapshot_hash TEXT DEFAULT '', agent_model TEXT DEFAULT '', environment_fingerprint TEXT DEFAULT '', base_commit TEXT DEFAULT '', subagent_run_id TEXT DEFAULT '', child_index INTEGER DEFAULT 0, async_dir TEXT DEFAULT '', result_json TEXT DEFAULT '', error TEXT DEFAULT '', integrated_patch_path TEXT DEFAULT '', integrated_patch_hash TEXT DEFAULT '', integrated_at TEXT DEFAULT '', artifact_saved_at TEXT DEFAULT '', candidate_run_id TEXT DEFAULT '', candidate_patch_hash TEXT DEFAULT '', review_fix_cycle INTEGER DEFAULT 0, profile_version INTEGER DEFAULT 0, profile_hash TEXT DEFAULT '', advanced_at TEXT DEFAULT '', migration_status TEXT DEFAULT 'legacy', created_at TEXT DEFAULT (datetime('now')), updated_at TEXT DEFAULT (datetime('now')), completed_at TEXT DEFAULT '', UNIQUE(task_id, stage, attempt))`
const WorkItemEscalationsTableSQL = `CREATE TABLE IF NOT EXISTS work_item_escalations (id TEXT PRIMARY KEY, work_item_id TEXT NOT NULL REFERENCES work_items(id) ON DELETE CASCADE, pipeline_run_id TEXT NOT NULL UNIQUE REFERENCES pipeline_runs(id), instruction_pack_id TEXT NOT NULL, instruction_pack_version INTEGER NOT NULL, instruction_pack_hash TEXT NOT NULL, level TEXT NOT NULL CHECK(level IN ('L2','L3')), status TEXT NOT NULL CHECK(status IN ('open','resolved')), report_json TEXT NOT NULL, resolution_json TEXT DEFAULT '', resolved_by TEXT DEFAULT '', created_at TEXT DEFAULT (datetime('now')), resolved_at TEXT DEFAULT '')`
const WorkItemCompletionReportsTableSQL = `CREATE TABLE IF NOT EXISTS work_item_completion_reports (id TEXT PRIMARY KEY, work_item_id TEXT NOT NULL REFERENCES work_items(id) ON DELETE CASCADE, pipeline_run_id TEXT NOT NULL UNIQUE REFERENCES pipeline_runs(id), instruction_pack_id TEXT NOT NULL, instruction_pack_version INTEGER NOT NULL, instruction_pack_hash TEXT NOT NULL, status TEXT NOT NULL CHECK(status IN ('done','partial','blocked')), summary TEXT DEFAULT '', report_markdown TEXT DEFAULT '', created_at TEXT DEFAULT (datetime('now')))`
const WorkItemProfilesTableSQL = `CREATE TABLE IF NOT EXISTS work_item_profiles (
	id TEXT PRIMARY KEY,
	work_item_id TEXT NOT NULL REFERENCES work_items(id) ON DELETE CASCADE,
	profile_name TEXT NOT NULL CHECK(profile_name IN ('plan','implement','qa')),
	profile_version INTEGER NOT NULL CHECK(profile_version>0),
	planning_depth TEXT NOT NULL CHECK(planning_depth IN ('quick','standard','designed','full')),
	stages_json TEXT NOT NULL,
	content_hash TEXT NOT NULL,
	resolved_at TEXT DEFAULT (datetime('now')),
	UNIQUE(work_item_id, profile_name, profile_version)
)`
